### ISSUE TITLE
[EPIC] Springboot Test Slice - Improve test efficiency and enable parallelism 

### ISSUE THREAD

**Issue by nramc** [nramc/journey-api#249]
- [x] Repositories: 
- [x] Resource: Create User 
- [x] Resource: Login Resource
- [x] Resource: GuestLogin
- [x] Resource: CreateJourney
- [x] Resource: Delete Journey
- [x] Resources: Fetch all categories -  https://github.com/nramc/journey-api/issues/278
- [x] Resource: Find Journey by ID - https://github.com/nramc/journey-api/issues/279
- [x] Resource: Find Journeys by Query - https://github.com/nramc/journey-api/issues/280
- [x] Resource: Find Published Journeys - https://github.com/nramc/journey-api/issues/281
- [x] Resources: Statics - https://github.com/nramc/journey-api/issues/282
- [x] Resources: Update Journey basic details - https://github.com/nramc/journey-api/issues/283https://github.com/nramc/journey-api/issues/283
- [x] Resources: Update Journey Geo details - https://github.com/nramc/journey-api/issues/284
- [x] Resources: Update Journey images details - https://github.com/nramc/journey-api/issues/285
- [x] Resources: Update Journey videos details - https://github.com/nramc/journey-api/issues/286
- [x] Resources: Update Journey Publish details - https://github.com/nramc/journey-api/issues/295
- [x] Resources: Timeline data - https://github.com/nramc/journey-api/issues/296
- [x] Resources: Change Password - https://github.com/nramc/journey-api/issues/297
- [x] Resources: Delete users - https://github.com/nramc/journey-api/issues/298
- [x] Resources: Find users - https://github.com/nramc/journey-api/issues/299
- [x] Resources: User security email attribute resource - https://github.com/nramc/journey-api/issues/300
- [x] Resources: Email Code Verification resource - https://github.com/nramc/journey-api/issues/301
- [x] Resources: TOTO Resource - https://github.com/nramc/journey-api/issues/302
- [x] Resources: Update user - https://github.com/nramc/journey-api/issues/303
- [ ]
